### ISSUE TITLE
Add in Image Optimize + Resmush.it

### ISSUE THREAD

**Issue by labboy0276** [thinktandem/minimis#22]
Add:
imageapi_optimize && imageapi_optimize_resmushit to profile install also include these files:

imageapi_optimize.settings.yml
```yaml
default_pipeline: resmush_it
```

imageapi_optimize.pipeline.resmush_it.yml
```yaml
langcode: en
status: true
dependencies:
  module:
    - imageapi_optimize_resmushit
name: resmush_it
label: ReSmush.it
processors:
  ac16b000-0edb-4e26-8cd6-dfe87b4a4989:
    uuid: ac16b000-0edb-4e26-8cd6-dfe87b4a4989
    id: resmushit
    weight: 1
    data:
      quality: 70
```

image.style.original_image.yml
```yaml
langcode: en
status: true
dependencies: {  }
name: original_image
label: 'Original Image'
effects: {  }
pipeline: __default__
```

core.entity_view_display.media.image.default.yml
```yaml
langcode: en
status: true
dependencies:
  config:
    - field.field.media.image.field_media_image
    - image.style.original_image
    - media.type.image
  module:
    - image
    - lazy
_core:
  default_config_hash: Mcr_LBmKv4rmmFEGxvJjcQX82Mch48BPQ_v3O8fYeXM
id: media.image.default
targetEntityType: media
bundle: image
mode: default
content:
  field_media_image:
    weight: 0
    label: hidden
    settings:
      image_style: original_image
      image_link: ''
    third_party_settings:
      lazy:
        lazy_image: '1'
    type: image
    region: content
hidden:
  created: true
  name: true
  thumbnail: true
  uid: true
```
